### PR TITLE
fix: yarn.go to return yarn instead of yarn.exe

### LINKED ISSUE #2728: ```mage ui``` not working on Windows OS
**Describe the bug**
Currently, ```mage ui``` command is not working on Windows OS, and giving the following error

image

**Files Or Markdown that can reproduce the issue**
- git clone the armada project
- install necessary dependencies
- run ```mage ui```

**Expected behavior**
The command was expected to install yarn packages for the ```internal/lookout/``` directory

**Actual behavior**
It is giving an error that the executable is not found in environment variables, though there exists a yarn bin inside the system environment variables.

**Why is the error occurring?**
We are using the ```binaryWithExt``` function to get the ```.exe``` version of ```yarn```, i.e., ```yarn.exe```, which is not the case for Windows OS, since yarn is a binary which can be directly executed with ```yarn``` command, without the ```.exe``` extension.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-514) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by anshgoyalevil**
#### What type of PR is this?
This PR modifies the ```yarn.go``` file to return ```yarn``` instead of ```yarn.exe``` for Windows OS.

Fixes #2728 

#### Special notes for your reviewer:

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-515) by [Unito](https://www.unito.io)

### CODE REVIEW

File: magefiles/yarn.go [hunk 1]
```diff
@@ -8,7 +8,7 @@ import (
 
 // Create golang code to build the UI
 func yarnBinary() string {
-	return binaryWithExt("yarn")
+	return "yarn"
```
Comment (kannon92) [inline magefiles/yarn.go:11]: I think this change is incorrect.  Does this work on native windows?

**Review by kannon92 — APPROVED** [review]
Reading about `yarn` on windows this seems to be correct.
